# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ofo_2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ofo_2
#pod 'Kingfisher'
#pod 'SnapKit'
##pod 'RxSwift'
##pod 'RxCocoa'
#pod 'AMapSearch-NO-IDFA'
#pod 'AMapLocation-NO-IDFA'
#pod 'AMapNavi-NO-IDFA'
#pod 'FTIndicator'
#pod 'swiftScan'
#pod 'SwiftySound'
#pod 'SwiftyTimer'


end
